### ISSUE TITLE
 2.4.4 breaks compatibility mode for Twilio.TwiML

### ISSUE THREAD

**Issue by corsjune** [signalwire/signalwire-dotnet-lite#12]
This C# snippet  works in 2.4.3 but breaks when updated to 2.4.4

using Twilio.TwiML;

// See https://aka.ms/new-console-template for more information
var x = new VoiceResponse();
Console.WriteLine(x.Hangup().ToString());

**Comment by Astaelan** [comment]
Thank you for the report, I believe I found the issue and will repackage for nuget tomorrow. Watch for a 2.4.5 version, and I will also inform you here here once the package is up as well.

**Comment by Astaelan** [comment]
New package is up, closing ticket, please open a new ticket if there are further issues.

**Comment by corsjune** [comment]
Thank you. That worked
